<<<<<<< HEAD
destination: "public"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]

# Custom Local Config
# ga_tracking_code: "UA-9046230-6"
subsite: opensource
subsite_name: Socrata Open Source
github_repo: "https://github.com/socrata/open-source.socrata.com"
icon: fa fa-git
